### PR TITLE
Add a basic installation guide

### PR DESCRIPTION
**Pull request by ADTC**
A basic guide explaining what you need to do to get this project up and running. I found that the list of dependencies in "What do I need?" do not form a good installation guide.

In my own experience of getting the package working in Atom, I found it to be exceedingly complex and unguided. I created a detailed guide as [a post in my blog](http://thehunk.blogspot.com/2017/10/convert-atom-editor-into-php-ide-using.html) to hopefully help anyone who needs it.

That's when I realized the readme here lacks a basic guide on how to get the package working properly. Hence I am making this PR.

Screenshot _(I didn't hack your site_ 😆 _- this is done through Inspect)_:
image

PS: This should probably be ported to the readme in [php-integrator/atom-base](https://github.com/php-integrator/atom-base) as well.

### CODE REVIEW

**Comment by Gert-dev** [comment]
First off, thanks for blogging about php-integrator and contributing!

This pull request sounds like a good idea to me. I agree that the requirements themselves don't necessarily make for a good installation guide. At best, they aren't easy to digest if you want to get things up and running quickly.

A small suggestion that I have is to perhaps make the PHP setup steps the first ones, that way the following steps can be the installation of the base package, in which the user will usually also need to configure the PHP binary path explicitly if it's not in his or her PATH (you could mention something like "and review the settings via Settings → ..."). This way you don't start in Atom, switch away to install PHP and come back to Atom later to fill in the details, but skip one switch.

Finally, could you follow "How do I make it work" with the words "in Atom"? Currently php-integrator doesn't really work anywhere else, but it makes it a little bit more explicit for people scrolling over the page.

**Comment by ADTC** [comment]
Hey thanks for writing back. Alight let me do that. It sounds like a good idea. :)

**Comment by ADTC** [comment]
Is it really necessary to mention "in Atom"? The page subtitle itself is "PHP code analysis and utilities **for the Atom editor**", all the screenshots are of Atom, there are mentions about Atom packages, and there is a later question "Is it really exclusive to Atom?". I don't know, but it seems pretty obvious already. But I can add it if you feel it's necessary.

Anyway I have done the rearrange and addition of PHP binary hint. How does it look?:
image

**Comment by Gert-dev** [comment]
Thanks for the changes. You have a valid point. In the future the "for the Atom editor" may disappear once the core is handling more of the lifting the Atom packages currently do, but at that point I'll have to review the rest of the page as well anyway, so I might as well add that at that point.

The rest looks good to me, thanks for contributing!

**Comment by ADTC** [comment]
You are very welcome, and thank you for the merges :)

**Pull request merged**
